# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Mavenjob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'microservices'
              organization: 'gitbubbals'
              scannerMode: 'Other'
          - task: Maven@3
            inputs:
              mavenPomFile: 'calc-service/pom.xml'
              goals: 'verify'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(agent.builddirectory)'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
          - task: SendMessage@1
            inputs:
              awsCredentials: 'Bals_aws_durk'
              regionName: 'us-east-1'
              message: 'hai dude this is from azure'
              topicArn: 'arn:aws:sns:us-east-1:177400249537:codestar-notifications-greetings'
  - stage: 'deploy'
    displayName: "deploy yo to webservice"
    dependsOn: Build
    jobs: 
    
    - deployment: Deploy 
      variables:
        - group: Release
      pool:
        vmImage: 'ubuntu-18.04'
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
 
            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy: website'
              inputs:
                azureSubscription: 'Free Trial(35592fcc-f495-4015-8cb8-d1080f32afc6)'
                appType: 'webAppLinux'
                appName: '$(webappname)'
                package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'