---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deploy
  labels:
    app: calc-app
    test: test
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: calc-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
      - name: calc-app
        image: manug2018/calc-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
