apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html-app
spec:
  type: LoadBalancer
  selector:
    app: html-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
